services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - gm-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    volumes:
      - db_data:/app/src/db
    networks:
      - gm-network
    restart: always

volumes:
  db_data:

networks:
  gm-network:
    name: gm-network  # 明示的に名前を指定
